name: Daily Registration

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点运行（UTC 时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 运行注册脚本
        run: python register.py
